all:
  hosts:
    127.0.0.1:
      ansible_connection: local

  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_nophrase
