---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      become: true
      when: ansible_os_family == 'Debian'
      changed_when: false
      
- name: Run main playbook
  import_playbook: ../../playbooks/create-job.yml
