- name: Verify
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8085/"
        status_code:
          - 200
          - 403

    - name: Check job is state
      community.general.jenkins_job_info:
        name: "spipeline0"
        user: "admin"
        password: "admin"
        url: "http://127.0.0.1:8085"
        validate_certs: false
      retries: 15
      delay: 60
      register: jenkins_job_info
      until: >
        jenkins_job_info.jobs[0]['name'] == 'spipeline0' and
        'blue' in jenkins_job_info.jobs[0]['color']
